FROM docker.io/library/maven@sha256:a14628a26fbf156eb621b2f58421a86f4d9ab6971d28747ac29d0d12cec99fcd AS builder
RUN microdnf install -y gcc
WORKDIR /build
COPY ./ ./

RUN mvn package
RUN mkdir -p out
RUN mvn help:evaluate -q -Dexpression=project.version -DforceStdout > out/version
RUN mv oj-c99runner/target/oj-c99runner-$(cat out/version)-jar-with-dependencies.jar out/oj-c99runner.jar

FROM docker.io/library/openjdk@sha256:52809b47f22be03496269ea5b5ca6f6259f0a44c60547791149021feb9619c96
RUN microdnf install -y gcc && microdnf clean all
COPY --from=builder /build/out /oj-c99runner

RUN useradd -r oj-c99runner
USER oj-c99runner
EXPOSE 1993

ENV RUNNER_ADDRESS 0.0.0.0
ENV RUNNER_PORT 1993

CMD java -jar /oj-c99runner/oj-c99runner.jar
