FROM docker.io/library/maven@sha256:84b220bb261d822e2ccf58ab3035f55bbdb00c13c42aa34a8992570171a77c1f AS builder
RUN microdnf install -y gcc
WORKDIR /build
COPY ./ ./

RUN mvn package
RUN mkdir -p out
RUN mvn help:evaluate -q -Dexpression=project.version -DforceStdout > out/version
RUN mv oj-server/target/oj-server-$(cat out/version)-jar-with-dependencies.jar out/oj-server.jar

FROM docker.io/library/openjdk@sha256:53941e9d89421c4aa85fa8f1fb22e1d5ae4697d385baa2e269fe6502b5eff591
COPY --from=builder /build/out /oj-server

RUN useradd -m -d /run/oj-server -r oj-server
USER oj-server
VOLUME /data
EXPOSE 8080

ENV ADDRESS 0.0.0.0
ENV PORT 8080
ENV DB_HOST localhost
ENV DB_NAME online_judge
# ENV DB_USER
# ENV DB_PASSWD
ENV DATA /data

WORKDIR /run/oj-server
CMD java -jar /oj-server/oj-server.jar
