FROM docker.io/library/maven@sha256:6ef014c142ea5c3582920ea254920c463d3578b57189e4048044fe3a6cb5fed2 AS builder
RUN microdnf install -y gcc
WORKDIR /cache
COPY ./pom.xml ./
COPY ./oj-c99runner/pom.xml ./oj-c99runner/
COPY ./oj-core/pom.xml ./oj-core/
COPY ./oj-judge/pom.xml ./oj-judge/
COPY ./oj-server/pom.xml ./oj-server/
RUN mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
WORKDIR /build
COPY ./ ./

RUN mvn package
RUN mkdir -p out
RUN mvn help:evaluate -q -Dexpression=project.version -DforceStdout > out/version
RUN mv oj-judge/target/oj-judge-$(cat out/version)-jar-with-dependencies.jar out/oj-judge.jar

FROM docker.io/library/openjdk@sha256:26ba405e50bea674fcab934c209e001c28e3da22a8678eabc73544655ff26734
COPY --from=builder /build/out /oj-judge

RUN useradd -r oj-judge
USER oj-judge
VOLUME /data

ENV RUNNER_HOST localhost
ENV RUNNER_PORT 1993
ENV DB_HOST localhost
ENV DB_NAME online_judge
# ENV DB_USER
# ENV DB_PASSWD
ENV DATA /data

CMD java -jar /oj-judge/oj-judge.jar
