FROM maven@sha256:8cf35e3e17d946b3cb51acc34c501fc8a2a07dc478c153743a50ae8d3b4783ee as build
RUN microdnf install -y shadow-utils && useradd builder
WORKDIR /build
RUN chown builder:builder /build
USER builder
COPY --chown=builder ./ ./

RUN mvn package
RUN mkdir -p out
RUN mvn help:evaluate -q -Dexpression=project.version -DforceStdout > out/version
RUN mv oj-c99runner/target/oj-c99runner-$(cat out/version)-jar-with-dependencies.jar out/oj-c99runner.jar

FROM openjdk@sha256:b25df6e6048e8c4995530d8e5b3e9b1468dcf642f1ba4baac89a4f3ca025f2be
RUN microdnf install -y shadow-utils gcc && microdnf clean all
COPY --from=build /build/out /oj-c99runner

RUN useradd -r oj-c99runner
USER oj-c99runner
EXPOSE 1993

ENV RUNNER_ADDRESS 0.0.0.0
ENV RUNNER_PORT 1993

CMD java -jar /oj-c99runner/oj-c99runner.jar
