FROM docker.io/library/maven@sha256:a4101605dde73c09367b541a78a78b026742f24d750aeaa8072391a714a2020d AS builder
RUN microdnf install -y gcc
WORKDIR /build
COPY ./ ./

RUN mvn package
RUN mkdir -p out
RUN mvn help:evaluate -q -Dexpression=project.version -DforceStdout > out/version
RUN mv oj-judge/target/oj-judge-$(cat out/version)-jar-with-dependencies.jar out/oj-judge.jar

FROM docker.io/library/openjdk@sha256:3f032cf26beef3150eb2abb5144dfdbfdf9d25cef0580d8b68af9eb0035d47db
COPY --from=builder /build/out /oj-judge

RUN useradd -r oj-judge
USER oj-judge
VOLUME /data

ENV RUNNER_HOST localhost
ENV RUNNER_PORT 1993
ENV DB_HOST localhost
ENV DB_NAME online_judge
# ENV DB_USER
# ENV DB_PASSWD
ENV DATA /data

CMD java -jar /oj-judge/oj-judge.jar
