name: GitLab CI
on: [push]
jobs:
  GitLab-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab CI
        shell: bash
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run:
          # GitHub-hosted runners execute code within ephemeral and clean isolated virtual machines,
          # meaning there is no way to persistently compromise this environment, or otherwise gain
          # access to more information than was placed in this environment during the bootstrap process.
          # Thus, it is OK to include secrets in the commands line arguments.
          # See: https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#hardening-for-self-hosted-runners
          curl -X POST -F token="$GITLAB_TOKEN"
                       -F ref=main
                       -F "variables[FROM_GITHUB]=true"
                       -F "variables[GITHUB_REF]=$GITHUB_REF"
                       -F "variables[GITHUB_SHA]=$GITHUB_SHA"
               -s https://git.boleyn.su/api/v4/projects/98/trigger/pipeline >/dev/null
